/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.ifmg.projeto_haras.view;

import com.ifmg.projeto_haras.view.gerenciaveis.IFrBaia;
import javax.swing.JFrame;

/**
 *
 * @author gusta
 */
public class FrAdministrador extends javax.swing.JFrame {

    private JFrame telaAnterior;
    /**
     * Creates new form FrAdministrador
     * @param telaQueChamou
     */
    public FrAdministrador(JFrame telaQueChamou) {
        this.telaAnterior = telaQueChamou;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deskPaneAdm = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdministrador = new javax.swing.JMenu();
        mnItemEquinoCad = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mitemGerenciarBaia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout deskPaneAdmLayout = new javax.swing.GroupLayout(deskPaneAdm);
        deskPaneAdm.setLayout(deskPaneAdmLayout);
        deskPaneAdmLayout.setHorizontalGroup(
            deskPaneAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 754, Short.MAX_VALUE)
        );
        deskPaneAdmLayout.setVerticalGroup(
            deskPaneAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 491, Short.MAX_VALUE)
        );

        menuAdministrador.setText("Equinos");

        mnItemEquinoCad.setText("Cadastro");
        mnItemEquinoCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnItemEquinoCadActionPerformed(evt);
            }
        });
        menuAdministrador.add(mnItemEquinoCad);

        jMenuBar1.add(menuAdministrador);

        jMenu2.setText("Proprietário");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Cuidador");

        jMenuItem4.setText("Cadastro");
        jMenu3.add(jMenuItem4);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Veterinário");

        jMenuItem2.setText("Cadastro");
        jMenu4.add(jMenuItem2);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Baias");

        mitemGerenciarBaia.setText("Gerenciar");
        mitemGerenciarBaia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mitemGerenciarBaiaActionPerformed(evt);
            }
        });
        jMenu5.add(mitemGerenciarBaia);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(deskPaneAdm)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(deskPaneAdm)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemEquinoCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnItemEquinoCadActionPerformed

    }//GEN-LAST:event_mnItemEquinoCadActionPerformed

    private void mitemGerenciarBaiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mitemGerenciarBaiaActionPerformed
        IFrBaia ifrBaia = new IFrBaia();
        deskPaneAdm.add(ifrBaia);
        ifrBaia.setVisible(true);
    }//GEN-LAST:event_mitemGerenciarBaiaActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setExtendedState(MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane deskPaneAdm;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenu menuAdministrador;
    private javax.swing.JMenuItem mitemGerenciarBaia;
    private javax.swing.JMenuItem mnItemEquinoCad;
    // End of variables declaration//GEN-END:variables
}
